model: gpt-4o # Pick your OpenAI model
source_language: DE # Set to whatever your source material language is
target_language: EN-US # Set to whatever your preferred output language is
language_levels: # Set the skill level of the questions asked (source material will be split equally.)
  - A1
  - A2
  # - B1
  # - B2
source_data_path: data/source_material.csv
output_dir: data/anki_decks
system_instructions: system_instructions/grammar_generator_agent.txt
language_specific_instructions:
  DE: system_instructions/language_specific/german_instructions.txt
  # Add any specific instructions for your source language here, see DE file as example